[package]
name = "days"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.46.1"
helpers = { path = "../helpers" }
rayon = "1.8.0"
